export { default as Dashboard } from './Dashboard'
export { default as Error } from './Error'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as MyDiet } from './MyDiet'
export { default as Chat } from './chat/Chat'